AWSTemplateFormatVersion: "2010-09-09"
Description: ELB Resources
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData: 
        BlockDeviceMappings: 
          - Ebs:
              VolumeSize: 22
              VolumeType: gp3
            DeviceName: /dev/xvda
        ImageId: ami-0d2fb06f3c1484132
        InstanceType: t2.micro
        KeyName: AWS-Sydney-KP	
        SecurityGroupIds:
          - sg-056ff6840df673e2f
        TagSpecifications:
          - ResourceType: instance
            Tags: 
              - Key: Environment
                Value: Production
              - Key: Ec2
                Value: ForShizzle
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash
              yum update -y
              yum install httpd -y
              systemctl start httpd
              systemctl enable httpd
              cd /var/www/html
              echo "this is a test page" > index.html
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: MyASG
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      AvailabilityZones:
        - ap-southeast-2a
        - ap-southeast-2b
        - ap-southeast-2c
      TargetGroupARNs:
        - !Ref TargetGroup
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: MyALB
      Scheme: internet-facing
      SecurityGroups: 
        - sg-056ff6840df673e2f
      Subnets: 
        - subnet-87be29df
        - subnet-6ee1f727
        - subnet-84b155e2
      Type: application
      Tags: 
        - Key: Environment
          Value: Production
        - Key: FullySic
          Value: Defo
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 80
      Protocol: HTTP
      LoadBalancerArn: !Ref ALB
      DefaultActions:
        - Order: 1
          TargetGroupArn: !Ref TargetGroup
          Type: "forward"
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: TG1
      Port: 80
      Protocol: HTTP    
      VpcId: vpc-557f4332  
Outputs:        
    ALBDNS:
        Description: ALB DNS
        Value: !GetAtt ALB.DNSName
