---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
       TemplateURL: https://dav-cloudformation.s3.ap-southeast-2.amazonaws.com/VPC.yaml
